### ISSUE TITLE
Do we need simple-call-tree and simple-call-tree-ext?

### ISSUE THREAD

**Issue by tarsius** [vapniks/simple-call-tree#3]
@vapniks did you ever ask @kensanata if your fork could be come the new one and only version?

**Comment by kensanata** [comment]
Please somebody take over as maintainer – I never used the code. Thank you!

## 

Typed on a tiny keyboard. Sorry for being terse.

**Comment by vapniks** [comment]
I think I might have sent @kensanata an email some time ago letting him know about `simple-call-tree-ext.el`, but I don't remember saying anything about replacing the original.

**Comment by tarsius** [comment]
> but I don't remember saying anything about replacing the original.

Well, that's kinda on the table now. Would be great if you could do it, but of course you are no obligated to do so.

**Comment by tarsius** [comment]
I've also noticed that while you are using github now, there are also some older packages which you have not migrated there yet. What's the status of those? `bs-ext` is the only one I can find right now, but I believe to remember there were more. Could you maybe create repositories for these packages?

**Comment by vapniks** [comment]
If there are any that are missing let me know which ones, but I'm fairly sure all my elisp packages are on github. With regard to simple-call-tree-ext.el do you suggest I rename it to simple-call-tree.el, and @kensanata remove simple-call-tree.el from emacswiki?

**Comment by kensanata** [comment]
Whatever works best for you. I no longer use it.

**Comment by tarsius** [comment]
@vapniks Yes, I think you should do that.

**Comment by vapniks** [comment]
Done

**Comment by tarsius** [comment]
Thanks. The Emacsmirror and Melpa should be adjusted shortly.
